#!/bin/bash
var1=$1
echo $var1

./atitool -vddgfx=1.05
./atitool -vddcr_soc=1.05
#./atitool -Fclk=$(($var1+50))
./atitool -i=0 -Fclk=1400
./atitool -i=0 -socclk=$((300/$var1))
./atitool -i=0 -Mem=$((167/$var1))
./atitool -i=0 -Eng=$((300/$var1))

./atitool -i=1 -Fclk=1400
./atitool -i=1 -socclk=$((300/$var1))
./atitool -i=1 -Mem=$((167/$var1))
./atitool -i=1 -Eng=$((300/$var1))

./atitool -i=2 -Fclk=1400
./atitool -i=2 -socclk=$((300/$var1))
./atitool -i=2 -Mem=$((167/$var1))
./atitool -i=2 -Eng=$((300/$var1))

./atitool -i=3 -Fclk=1400
./atitool -i=3 -socclk=$((300/$var1))
./atitool -i=3 -Mem=$((167/$var1))
./atitool -i=3 -Eng=$((300/$var1))

#var2=$(($var1+25))
#var3=$(($var2+25))
#echo $var3

